using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedChatBot.Database
{
    class Get
    {
        //create sentence
        public static string GetSentence(SqlConnection conn, Random rand, int stopIndex)
        {
            List<int> wordIndexes = new List<int>();
            int wordIndex = GetRandomStartWord(conn);
            wordIndexes.Add(wordIndex);
            while (wordIndex != stopIndex)
            {
                List<Connection> connections = GetConnections(conn, wordIndex);
                int totalCount = connections.Sum(c => c.count);
                int random = rand.Next(totalCount) + 1;
                int count = 0;
                foreach (Connection c in connections)
                {
                    count += c.count;
                    if (count >= random)
                    {
                        wordIndex = c.second;
                        if (wordIndex != stopIndex)
                        {
                            wordIndexes.Add(wordIndex);
                        }
                        break;
                    }
                }
            }
            if (wordIndexes.Count > 0)
            {
                return GetWordsForSentence(conn, wordIndexes);
            }
            return "";
        }

        private static string GetWordsForSentence(SqlConnection conn, List<int> wordIndexes)
        {
            string sentence = "";
            for (int i = 0; i < wordIndexes.Count; i++)
            {
                using (SqlCommand command = new SqlCommand("SELECT word FROM Words WHERE id=@id", conn))
                {
                    command.Parameters.AddWithValue("@id", wordIndexes[i]);
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            if (reader.Read())
                            {
                                sentence += (string)(reader.GetValue(0)) + " ";
                            }
                        }
                    }
                }
            }

            return sentence;
        }

        private static List<Connection> GetConnections(SqlConnection conn, int wordIndex)
        {
            List<Connection> connections = new List<Connection>();
            using (SqlCommand command = new SqlCommand("SELECT secondId, count FROM Connections WHERE firstId=@id", conn))
            {
                command.Parameters.AddWithValue("@id", wordIndex);
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            Connection connection = new Connection();
                            connection.first = wordIndex;
                            connection.second = (int)(reader.GetValue(0));
                            connection.count = (int)(reader.GetValue(1));
                            connections.Add(connection);
                        }
                    }
                }
            }
            return connections;
        }

        private static int GetRandomStartWord(SqlConnection conn)
        {
            using (SqlCommand command = new SqlCommand("SELECT TOP 1 wordId FROM StartWords ORDER BY NEWID()", conn))
            {
                using (SqlDataReader reader = command.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        if (reader.Read())
                        {
                            return (int)(reader.GetValue(0));
                        }
                    }
                }
            }
            return -1;
        }
    }
}
