using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedChatBot
{
    class markov
    {
        public markov(string w)
        {
            word = w;
            count = 1;
        }
        public string word { get; set; }
        public int count { get; set; }
    }

    class chain
    {
        public chain(string w)
        {
            word = w;
            count = 1;
            markovs = new List<markov>();
        }
        public string word { get; set; }
        public int count { get; set; }
        public List<markov> markovs;
    }
}
