using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoGeneratedChatBot
{
    class Connection
    {
        public int first { get; set; }
        public int second { get; set; }
        public int count { get; set; }
    }
}
