using System;

namespace AutoGeneratedChatBot
{
    class Program
    {
        static void Main(string[] args)
        {
            TextGenerator gen = new TextGenerator();
            Console.WriteLine("Type 'start' or 'stop' to (de)activate bot");
            while (true)
            {
                string input = Console.ReadLine();
                if (input.ToLower() == "stop")
                {
                    gen.Stop();
                }
                else if (input.ToLower() == "start")
                {
                    gen.Run();
                }
            }
        }
    }
}
