using System;
using Telegram.Bot;
using Telegram.Bot.Args;
using Telegram.Bot.Types.Enums;
using Telegram.Bot.Types;
using System.Linq;
using Wolfram.Alpha;

namespace AutoGeneratedChatBot
{
    class TextGenerator
    {
        private static readonly TelegramBotClient bot = new TelegramBotClient("782389542:AAG8dI6JEbs-7exXG1fMpE02iJmyobgHWeo");
        private static readonly WolframAlphaService wolfram = new WolframAlphaService("LQ84PR-AA8GG755W6");
        private static Yandex.Translator.IYandexTranslator translator;
        private static Reddit reddit;
        private static Random rand = new Random();
        private static Int64 chatID = -1001401117617;
        private static int messageCounter = 0;
        private static int messageRandom;
        private static int banCounter = 0;
        private static int banRandom;
        private static User me;
        private static bool running = false;
        private static int stopIndex = -1;

        private static DbManager db = new DbManager();

        public TextGenerator()
        {
            reddit = new Reddit();
            messageRandom = rand.Next(4, 7);
            banRandom = rand.Next(500, 1000);
            me = bot.GetMeAsync().Result;
            Console.Title = me.Username;
            bot.OnMessage += BotOnMessageReceived;
        }

        public void Run()
        {
            if (!running)
            {
                translator = Yandex.Translator.Yandex.Translator(api => api.ApiKey("trnsl.1.1.20190209T140513Z.e7b72a349e848bdd.5958c64ea2df19c399ba9f12a17ccd1711ea450a"));
                db.Open();
                bot.StartReceiving();
                Console.WriteLine($"Start listening for @{me.Username}");
                //var start = bot.SendTextMessageAsync(chatID, "Guess who's back? Fucking " + me.FirstName + " is back bitches.\r\nType /help for all the shit I can do.").Result;
                running = true;
            }
        }

        public void Stop()
        {
            if (running)
            {
                bot.StopReceiving();
                db.Close();
                Console.WriteLine($"Stop listening for @{me.Username}");
                //var end = bot.SendTextMessageAsync(chatID, "RIP " + me.FirstName).Result;
                running = false;
            }
        }

        private static void SendMessage(int count, bool story)
        {
            if (stopIndex == -1)
            {
                stopIndex = db.GetStopWord();
            }
            else
            {
                string message = "";
                for (int i = 0; i < count; i++)
                {
                    message += db.GetSentence(stopIndex, story) + "\n\n";
                }
                if (!string.IsNullOrWhiteSpace(message))
                {
                    var send = bot.SendTextMessageAsync(chatID, message);
                }
            }
        }

        private static void BotOnMessageReceived(object sender, MessageEventArgs messageEventArgs)
        {
            banCounter++;
            var message = messageEventArgs.Message;
            if (message == null || message.Type != MessageType.Text) return;
            if (message.Text == null || string.IsNullOrEmpty(message.Text)) return;
            if (message.Chat.Id != chatID)
            {
                return;
            }
            if(message.Text.StartsWith("/help"))
            {
                var send = bot.SendTextMessageAsync(chatID, "/talkbitch\r\n");
            }
            else if (message.Text.StartsWith("/stats"))
            {
                string answer = db.GetStats();
                if (!string.IsNullOrWhiteSpace(answer))
                {
                    var send = bot.SendTextMessageAsync(chatID, answer);
                }
            }
            else if (message.Text.StartsWith("/talk"))
            {
                SendMessage(5, false);
            }
            else if (message.Text.StartsWith("/story"))
            {
                SendMessage(1, true);
            }
            else if (message.Text.StartsWith("/r"))
            {
                string answer = reddit.GetSubreddit(message.Text);
                if (!string.IsNullOrWhiteSpace(answer))
                {
                    var send = bot.SendTextMessageAsync(chatID, answer);
                }
            }
            else if (!message.Text.StartsWith("/") && !message.Text.StartsWith("@"))
            {
                if (message.Text.EndsWith("?"))
                {
                    string translation = Wolfram.GetTranslation(translator, message.Text);
                    string answer = Wolfram.AskWolfram(wolfram, translation);
                    if (!string.IsNullOrWhiteSpace(answer))
                    {
                        var send = bot.SendTextMessageAsync(chatID, answer);
                    }
                }
                string[] alineas = message.Text.Split('\n');
                foreach (string a in alineas)
                {
                    if (!string.IsNullOrWhiteSpace(a))
                    {
                        AddSentence(a);
                    }
                }
                messageCounter++;
            }

            if (messageCounter >= messageRandom)
            {
                messageCounter = 0;
                messageRandom = rand.Next(4, 7);
                SendMessage(1, false);
            }
            if (banCounter >= banRandom)
            {
                ChatMember[] members = bot.GetChatAdministratorsAsync(chatID).Result;
                foreach (ChatMember member in members)
                {
                    if (!member.User.IsBot)
                    {
                        bot.RestrictChatMemberAsync(chatID, member.User.Id, DateTime.Now.AddMinutes(5), false, false, false, false);
                    }
                }
                banRandom = rand.Next(2000, 2500);
                banCounter = 0;
            }
        }

        private static void AddSentence(string input)
        {
            string temp = input;
            //check if parentheses are balanced if not trim them
            if (!Utilities.CheckParentheses(temp))
            {
                temp = temp.Trim(new char[] { '{', '}', '[', ']', '(', ')' });
            }
            //add dot so bot knows that a sentence is finished
            temp += " .";
            //split in words
            //remove empty and url's
            string[] words = temp.Split(' ');
            words = words.Where(x => !string.IsNullOrWhiteSpace(x) && !Uri.IsWellFormedUriString(x, UriKind.Absolute)).ToArray();
            db.AddWords(words);
        }
    }
}
